# Generated by Django 5.0.6 on 2024-06-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_nome_completo', models.CharField(max_length=255)),
                ('cliente_telefone', models.CharField(max_length=255)),
                ('cliente_email', models.CharField(max_length=255)),
                ('id_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('custo', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
